### ISSUE TITLE
Use functional options for Set instead of Setf

### ISSUE THREAD

**Issue by zpatrick** [ridgelines/go-cache#3]
Opinionated, but I think this reads better:
```go
c.Set(key, val)
c.Set(key, val, cache.Expire(time.Hour))
```

**Comment by ofonimefrancis** [comment]
Was this feature implemented?

**Comment by zpatrick** [comment]
It was! Totally forgot to update this issue, thanks.

Example usage [here](https://github.com/zpatrick/go-cache/blob/master/cache_test.go#L22)
